#!/bin/sh

echo '➜ Make "builder" directory.'
mkdir builder
cd builder

echo '➜ Download and unpack image builder.'
wget https://downloads.openwrt.org/snapshots/targets/bcm27xx/bcm2711/openwrt-imagebuilder-bcm27xx-bcm2711.Linux-x86_64.tar.xz
tar --strip-components=1 -xf openwrt-imagebuilder-bcm27xx-bcm2711.Linux-x86_64.tar.xz

echo '➜ Create feeds config.'
echo 'src-git packages https://git.openwrt.org/feed/packages.git' > feeds.conf

echo '➜ Update feeds.'
./scripts/feeds update

echo '➜ Build image.'
make image PROFILE=rpi-4 PACKAGES="python3"


